# frozen_string_literal: true

require 'open3'
require 'fileutils'

# Phase 11 Tier 4: CRuby 3.4 (miniruby)
#
# Compiles the CRuby interpreter using occ and verifies that the resulting
# miniruby binary can execute basic Ruby programs.
#
# Prerequisites (Phase 13 — GCC Extension Compatibility):
#   - Statement expressions ({ ... })
#   - __typeof__ with correct type reflection
#   - __builtin_offsetof computing correct offsets
#   - Alternate keyword spellings (__inline__, __volatile__, __asm__, etc.)
#   - __extension__ as a no-op keyword
#   - __builtin_clz / __builtin_ctz / __builtin_popcount
#   - Inline assembly (asm volatile("" ::: "memory"))
#
# Build strategy:
#   1. Clone ruby/ruby at a known tag
#   2. Run ./autogen.sh + ./configure using the system toolchain to generate
#      config.h, ruby/config.h, and other autoconf artefacts (occ is not used
#      for this step — configure requires a fully working C compiler)
#   3. Compile each miniruby source file to a .o with occ
#   4. Link all objects into miniruby using clang
#   5. Run smoke tests
#
# Run with:
#   THIRDPARTY=1 bundle exec rspec spec/phase11/ruby_spec.rb

RSpec.describe 'Phase 11: CRuby 3.4 miniruby (Tier 4)', :thirdparty do
  include ThirdpartyHelper

  RUBY_TAG    = 'v3_4_0'
  RUBY_REPO   = 'https://github.com/ruby/ruby.git'
  RUBY_CACHE  = File.join(ThirdpartyHelper::CACHE_DIR, 'ruby')

  # Core Ruby source files (NORMALMAINOBJ + COMMONOBJS + MINIOBJS) that form
  # miniruby. Generated by inspecting `make minirubymain` with Ruby v3_4_0.
  # vm_exec.c and vm_method.c are #include'd by vm.c — do not compile separately.
  MINIRUBY_SOURCES = %w[
    main.c
    array.c
    ast.c
    bignum.c
    class.c
    compar.c
    compile.c
    complex.c
    cont.c
    debug.c
    debug_counter.c
    dir.c
    dln_find.c
    dmydln.c
    encoding.c
    enum.c
    enumerator.c
    error.c
    eval.c
    file.c
    gc.c
    hash.c
    imemo.c
    inits.c
    io.c
    io_buffer.c
    iseq.c
    load.c
    marshal.c
    math.c
    memory_view.c
    miniinit.c
    node.c
    node_dump.c
    numeric.c
    object.c
    pack.c
    parse.c
    parser_st.c
    proc.c
    process.c
    ractor.c
    random.c
    range.c
    rational.c
    re.c
    regcomp.c
    regenc.c
    regerror.c
    regexec.c
    regparse.c
    regsyntax.c
    rjit.c
    rjit_c.c
    ruby.c
    ruby_exts.c
    ruby_parser.c
    scheduler.c
    shape.c
    signal.c
    sprintf.c
    st.c
    strftime.c
    string.c
    struct.c
    symbol.c
    thread.c
    time.c
    transcode.c
    util.c
    variable.c
    version.c
    vm.c
    vm_backtrace.c
    vm_dump.c
    vm_sync.c
    vm_trace.c
    weakmap.c
    addr2line.c
    missing/explicit_bzero.c
    missing/setproctitle.c
  ].freeze

  # Prism sources (Ruby 3.4 uses Prism as the default parser).
  # Includes both static and template-generated sources.
  PRISM_SOURCES = %w[
    prism/prism.c
    prism/api_pack.c
    prism/diagnostic.c
    prism/encoding.c
    prism/node.c
    prism/options.c
    prism/pack.c
    prism/prettyprint.c
    prism/regexp.c
    prism/serialize.c
    prism/static_literals.c
    prism/token_type.c
    prism/util/pm_buffer.c
    prism/util/pm_char.c
    prism/util/pm_constant_pool.c
    prism/util/pm_integer.c
    prism/util/pm_list.c
    prism/util/pm_memchr.c
    prism/util/pm_newline_list.c
    prism/util/pm_string.c
    prism/util/pm_strncasecmp.c
    prism/util/pm_strpbrk.c
    prism/extension.c
    prism/api_node.c
    prism_init.c
  ].freeze

  # Built-in encoding and transcoder objects (BUILTIN_ENCOBJS + BUILTIN_TRANSOBJS).
  ENC_SOURCES = %w[
    enc/ascii.c
    enc/us_ascii.c
    enc/unicode.c
    enc/utf_8.c
    enc/trans/newline.c
  ].freeze

  def autotools_available?
    system('which autoconf > /dev/null 2>&1') &&
      system('which ./configure > /dev/null 2>&1 || true')
  end

  def run_configure(build_dir)
    # autogen.sh generates ./configure from configure.ac
    unless system('bash autogen.sh > /dev/null 2>&1', chdir: build_dir)
      skip 'ruby autogen.sh failed — autoconf may not be installed'
    end

    # Run configure with system clang to produce config.h and friends.
    # --disable-rubygems and --without-* keep the build minimal.
    configure_flags = %w[
      --disable-rubygems
      --disable-install-doc
      --without-gmp
      --with-static-linked-ext
    ]
    _out, err, st = Open3.capture3(
      './configure', *configure_flags,
      chdir: build_dir
    )
    unless st.success?
      skip "ruby ./configure failed:\n#{err.slice(0, 500)}"
    end
  end

  def disable_unsupported_config(build_dir)
    config_paths = [
      File.join(build_dir, 'include', 'ruby', 'internal', 'config.h'),
      *Dir.glob(File.join(build_dir, '.ext', 'include', '*', 'ruby', 'config.h')),
      *Dir.glob(File.join(build_dir, '**', 'config.h')),
    ].uniq

    config_paths.each do |path|
      next unless File.file?(path)

      text = File.read(path)
      next unless text.include?('HAVE_INT128_T') ||
                  text.include?('SIZEOF_INT128_T') ||
                  text.include?('USE_RJIT')

      text = text.gsub(/^#define HAVE_INT128_T\b.*$/, '/* #undef HAVE_INT128_T */')
      text = text.gsub(/^#define SIZEOF_INT128_T\b.*$/, '/* #undef SIZEOF_INT128_T */')
      text = text.gsub(/^#define USE_RJIT\b.*$/, '#define USE_RJIT 0')
      File.write(path, text)
    end
  end

  it 'compiles miniruby and runs basic scripts', :slow do
    require_git!
    skip 'autoconf not available' unless system('which autoconf > /dev/null 2>&1')

    # ── 1. Clone source ────────────────────────────────────────────────────
    src_dir = git_clone(RUBY_REPO, RUBY_TAG, 'ruby')

    build_dir = Dir.mktmpdir('occ_ruby_')
    begin
      # Copy source into build dir so configure can write files there
      FileUtils.cp_r(Dir["#{src_dir}/*"], build_dir)
      FileUtils.cp_r(Dir["#{src_dir}/.[^.]*"].select { |f| File.file?(f) }, build_dir)

      # ── 2. Run ./configure with system toolchain ───────────────────────
      run_configure(build_dir)
      # Configure probes the host clang, which supports __int128. occ currently
      # parses __int128 as a 64-bit placeholder, so keep CRuby on its non-int128
      # fallback paths until real 128-bit lowering exists.
      disable_unsupported_config(build_dir)

      # ── 3. Generate parser and other generated files via make ─────────
      # parse.c/lex.c from parse.y; id.h/id.c; probes.h; insns_info.inc/node_name.inc from tools
      system('make parse.c lex.c id.h id.c probes.h known_errors.inc insns.inc insns_info.inc optinsn.inc optunifs.inc vmtc.inc vm.inc node_name.inc vm_call_iseq_optimized.inc BASERUBY=ruby 2>/dev/null',
             chdir: build_dir)

      # Generate prism template-derived headers (diagnostic.h, ast.h).
      # These are template-generated and not built by default until 'srcs' target
      # runs, but prism utility headers include them directly.
      %w[include/prism/diagnostic.h include/prism/ast.h].each do |tmpl_name|
        out_path = File.join(build_dir, 'prism', File.basename(tmpl_name))
        next if File.exist?(out_path)
        system("ruby prism/templates/template.rb #{tmpl_name} #{out_path} 2>/dev/null",
               chdir: build_dir)
      end

      # Generate prism template-derived C source files.
      {
        'src/diagnostic.c'      => 'prism/diagnostic.c',
        'src/node.c'            => 'prism/node.c',
        'src/prettyprint.c'     => 'prism/prettyprint.c',
        'src/serialize.c'       => 'prism/serialize.c',
        'src/token_type.c'      => 'prism/token_type.c',
        'ext/prism/api_node.c'  => 'prism/api_node.c',
      }.each do |tmpl_name, out_name|
        out_path = File.join(build_dir, out_name)
        next if File.exist?(out_path)
        system("ruby prism/templates/template.rb #{tmpl_name} #{out_path} 2>/dev/null",
               chdir: build_dir)
      end

      # Generate enc/trans/newline.c from newline.trans
      newline_c = File.join(build_dir, 'enc/trans/newline.c')
      unless File.exist?(newline_c)
        FileUtils.mkdir_p(File.dirname(newline_c))
        system("ruby tool/transcode-tblgen.rb -vo #{newline_c} enc/trans/newline.trans 2>/dev/null",
               chdir: build_dir)
      end

      # Generate miniprelude.c (included by mini_builtin.c which is included by miniinit.c).
      # Requires rbinc targets to be up to date first.
      rbinc_targets = (MINIRUBY_SOURCES + %w[warning.c]).filter_map do |s|
        rb = s.sub('.c', '.rb')
        File.exist?(File.join(build_dir, rb)) ? rb.sub('.rb', '.rbinc') : nil
      end
      extra_rbincs = %w[kernel.rbinc nilclass.rbinc timev.rbinc trace_point.rbinc thread_sync.rbinc yjit_hook.rbinc prelude.rbinc gem_prelude.rbinc yjit.rbinc].select do |r|
        File.exist?(File.join(build_dir, r.sub('.rbinc', '.rb')))
      end
      rbinc_targets = (rbinc_targets + extra_rbincs).uniq
      system("make -k #{rbinc_targets.join(' ')} BASERUBY=ruby 2>/dev/null",
             chdir: build_dir) if rbinc_targets.any?

      miniprelude_c = File.join(build_dir, 'miniprelude.c')
      unless File.exist?(miniprelude_c)
        system('make miniprelude.c BASERUBY=ruby 2>/dev/null', chdir: build_dir)
      end

      # Collect include paths that configure produces.
      # The platform-specific ext dir uses the Darwin kernel version (e.g. arm64-darwin25),
      # so glob for it rather than hard-coding the version number.
      ext_include_dir = Dir.glob("#{build_dir}/.ext/include/arm64-darwin*/").first ||
                        Dir.glob("#{build_dir}/.ext/include/*/").first
      unicode_hdr_dir = Dir.glob("#{build_dir}/enc/unicode/*/").first
      include_flags = [
        "-I#{build_dir}",
        "-I#{build_dir}/include",
        "-I#{build_dir}/prism",
        (ext_include_dir ? "-I#{ext_include_dir.chomp('/')}" : nil),
        (unicode_hdr_dir ? "-I#{unicode_hdr_dir.chomp('/')}" : nil),
      ].compact.select { |f| Dir.exist?(f.sub(/^-I/, '')) }
      include_flags += ['-I', ThirdpartyHelper::SDK_INCLUDE] if ThirdpartyHelper::SDK_INCLUDE

      # Add macOS framework search path so <Framework/Header.h> includes resolve
      sdk_path = `xcrun --show-sdk-path 2>/dev/null`.strip
      framework_flags = sdk_path.empty? ? [] : ['-F', File.join(sdk_path, 'System', 'Library', 'Frameworks')]

      base_compile_flags = include_flags + framework_flags + [
        '-c', '-DRUBY_EXPORT', '-DMINIRUBY',
        '-DDTRACE_PROBES_DISABLED=1',
        '-DUSE_TOKEN_THREADED_VM=0',
        '-DOPT_THREADED_CODE=3',
        '-D_XOPEN_SOURCE',
      ]

      # ── 4. Compile each miniruby source file with occ ──────────────────
      obj_files = []
      compile_errors = []

      all_sources = MINIRUBY_SOURCES + PRISM_SOURCES + ENC_SOURCES

      all_sources.each do |src_name|
        src_path = File.join(build_dir, src_name)
        next unless File.exist?(src_path)

        obj_name = src_name.sub('.c', '.o')
        obj_path = File.join(build_dir, obj_name)
        FileUtils.mkdir_p(File.dirname(obj_path))

        result = occ_compile(
          src_path,
          output: obj_path,
          flags: base_compile_flags
        )

        if result[:status] == 0
          obj_files << obj_path
        else
          compile_errors << "#{src_name}: #{result[:stderr].lines.first&.strip}"
        end
      end

      # ── 5. Compile ARM64 coroutine implementation (assembly) with clang ──
      coroutine_s = File.join(build_dir, 'coroutine/arm64/Context.S')
      if File.exist?(coroutine_s)
        coroutine_o = File.join(build_dir, 'coroutine/arm64/Context.o')
        FileUtils.mkdir_p(File.dirname(coroutine_o))
        if system("clang -c #{coroutine_s} -I#{build_dir} '-DPREFIXED_SYMBOL(name)=TOKEN_PASTE(_,name)' -o #{coroutine_o} 2>/dev/null")
          obj_files << coroutine_o
        end
      end

      expect(obj_files).not_to be_empty, 'no object files were produced'

      # Report compile errors but don't fail immediately — show progress
      if compile_errors.any?
        fail "#{compile_errors.length} file(s) failed to compile:\n" \
             "#{compile_errors.first(10).join("\n")}"
      end

      # ── 6. Link miniruby with clang ────────────────────────────────────
      miniruby_bin = File.join(build_dir, 'miniruby')
      _, link_err, link_st = Open3.capture3(
        'clang', *obj_files, '-o', miniruby_bin,
        '-lpthread', '-ldl', '-lm', '-liconv',
        '-framework', 'CoreFoundation'
      )
      expect(link_st.exitstatus).to eq(0),
        "link failed:\n#{link_err.slice(0, 5000)}"

      # ── 7. Smoke tests ────────────────────────────────────────────────
      # Helper: run a one-liner in miniruby, check exit status and stdout.
      miniruby_env = {
        'RUBYOPT' => nil,
        'RUBYLIB' => nil,
        'GEM_HOME' => nil,
        'GEM_PATH' => nil,
        'BUNDLE_BIN_PATH' => nil,
        'BUNDLE_GEMFILE' => nil,
        'BUNDLER_ORIG_BUNDLE_BIN_PATH' => nil,
        'BUNDLER_ORIG_BUNDLE_GEMFILE' => nil,
        'BUNDLER_ORIG_GEM_HOME' => nil,
        'BUNDLER_ORIG_GEM_PATH' => nil,
        'BUNDLER_ORIG_MANPATH' => nil,
        'BUNDLER_ORIG_PATH' => nil,
        'BUNDLER_ORIG_RB_USER_INSTALL' => nil,
        'BUNDLER_ORIG_RUBYLIB' => nil,
        'BUNDLER_ORIG_RUBYOPT' => nil,
      }
      mr = ->(code, expected, label = nil) {
        label ||= code.length > 60 ? "#{code[0, 57]}..." : code
        out, err, st = Open3.capture3(miniruby_env, miniruby_bin, '-e', code)
        expect(st.exitstatus).to eq(0),
          "#{label}: non-zero exit (binary: #{miniruby_bin})\n#{err.slice(0, 2000)}"
        expect(out.strip).to eq(expected.strip), label
      }

      # ── Integers and arithmetic ───────────────────────────────────────
      mr.call 'puts 1 + 1',                   '2'
      mr.call 'puts 2 ** 10',                 '1024'
      mr.call 'puts 17 % 5',                  '2'
      mr.call 'puts -7.divmod(3).inspect',    '[-3, 2]'
      mr.call 'puts 255.to_s(16)',             'ff'
      mr.call 'puts 0xff',                     '255'
      mr.call 'puts 10.gcd(6)',                '2'
      mr.call 'puts 5.lcm(6)',                 '30'

      # ── Floats and Math ───────────────────────────────────────────────
      mr.call 'puts (0.1 + 0.2).round(1)',     '0.3'
      mr.call 'puts Math.sqrt(144).to_i',      '12'
      mr.call 'puts 3.14.ceil',                '4'
      mr.call 'puts (-3.7).floor',             '-4'

      # ── Strings ───────────────────────────────────────────────────────
      mr.call 'puts "hello from occ"',         'hello from occ'
      mr.call 'puts "hello".upcase',            'HELLO'
      mr.call 'puts "WORLD".downcase',          'world'
      mr.call 'puts "hello world".split.length', '2'
      mr.call 'puts "abc" * 3',                 'abcabcabc'
      mr.call 'n = 42; puts "n=#{n}"',          'n=42'
      mr.call 'puts "hello".chars.sort.join',   'ehllo'
      mr.call 'puts "   trim   ".strip',        'trim'
      mr.call 'puts "hello world".gsub("l","L")', 'heLLo worLd'
      mr.call 'puts "hello"[1..3]',             'ell'
      mr.call 'puts "hello".start_with?("hel")', 'true'
      mr.call 'puts "a,b,c".split(",").inspect', '["a", "b", "c"]'
      mr.call 'puts "%05d" % 42',              '00042'

      # ── Arrays ────────────────────────────────────────────────────────
      mr.call 'puts [1,2,3].map{|x| x*x}.inspect', '[1, 4, 9]'
      mr.call 'puts [3,1,2].sort.inspect',          '[1, 2, 3]'
      mr.call 'puts [1,2,3,4,5].select(&:odd?).inspect', '[1, 3, 5]'
      mr.call 'puts [1,2,3,4,5].reject(&:even?).inspect', '[1, 3, 5]'
      mr.call 'puts [1,2,3].inject(:+)',             '6'
      mr.call 'puts [1,2,3,4,5].sum',                '15'
      mr.call 'puts [[1,2],[3,[4]]].flatten.inspect', '[1, 2, 3, 4]'
      mr.call 'puts [1,2,2,3].uniq.inspect',         '[1, 2, 3]'
      mr.call 'a = [1,2,3]; a.push(4); puts a.pop',  '4'
      mr.call 'puts [1,2,3].zip([4,5,6]).map{|a,b| a+b}.inspect', '[5, 7, 9]'
      mr.call 'puts [3,1,4,1,5].sort.first(3).inspect', '[1, 1, 3]'

      # ── Hashes ────────────────────────────────────────────────────────
      mr.call 'h={a:1,b:2,c:3}; puts h[:b]',             '2'
      mr.call 'h={a:1,b:2}; puts h.values.sort.inspect',  '[1, 2]'
      mr.call 'h={a:1,b:2}; puts h.map{|k,v| v*2}.sort.inspect', '[2, 4]'
      mr.call 'h={}; h[:x]=10; h[:y]=20; puts h.values.sum', '30'
      mr.call 'puts({a:1,b:2,c:3}.any?{|k,v| v>2})',      'true'
      mr.call 'puts({a:1,b:2,c:3}.count{|k,v| v.odd?})',   '2'

      # ── Ranges ────────────────────────────────────────────────────────
      mr.call 'puts (1..5).to_a.inspect',               '[1, 2, 3, 4, 5]'
      mr.call 'puts (1...5).to_a.inspect',              '[1, 2, 3, 4]'
      mr.call 'puts (1..10).select{|n| n.even?}.inspect', '[2, 4, 6, 8, 10]'
      mr.call 'puts (1..100).select{|n| n%15==0}.inspect', '[15, 30, 45, 60, 75, 90]'
      mr.call 'puts (1..5).include?(3)',                'true'

      # ── Control flow ──────────────────────────────────────────────────
      mr.call 'x=10; puts x>5 ? "big" : "small"',     'big'
      mr.call 'i=0; while i<5; i+=1; end; puts i',    '5'
      mr.call 'i=3; until i==0; i-=1; end; puts i',   '0'
      mr.call 'puts case 7; when 1..5 then "low"; when 6..10 then "mid"; else "high"; end', 'mid'
      mr.call '3.times{|i| print i}; puts',            '012'
      mr.call 'puts 5.downto(1).to_a.inspect',         '[5, 4, 3, 2, 1]'

      # ── Methods ───────────────────────────────────────────────────────
      mr.call 'def fact(n); n<=1 ? 1 : n*fact(n-1); end; puts fact(10)', '3628800'
      mr.call 'def hi(name="world"); "Hello, #{name}!"; end; puts hi; puts hi("Ruby")',
              "Hello, world!\nHello, Ruby!"
      mr.call 'def sum(*args); args.sum; end; puts sum(1,2,3,4,5)',    '15'
      mr.call 'def fib(n); n<2 ? n : fib(n-1)+fib(n-2); end; puts (0..7).map{|i| fib(i)}.inspect',
              '[0, 1, 1, 2, 3, 5, 8, 13]'

      # ── Classes ───────────────────────────────────────────────────────
      mr.call 'class Rect; def initialize(w,h); @w,@h=w,h; end; ' \
              'def area; @w*@h; end; end; puts Rect.new(3,4).area',
              '12', 'class with initialize'
      mr.call 'class Counter; def initialize; @n=0; end; ' \
              'def inc; @n+=1; end; def val; @n; end; end; ' \
              'c=Counter.new; 5.times{c.inc}; puts c.val',
              '5', 'stateful class'
      mr.call 'class Animal; def speak; "..."; end; end; ' \
              'class Dog < Animal; def speak; "Woof"; end; end; ' \
              'puts Dog.new.speak; puts Dog.new.is_a?(Animal)',
              "Woof\ntrue", 'inheritance'
      mr.call 'class Stack; def initialize; @s=[]; end; ' \
              'def push(v); @s<<v; self; end; def pop; @s.pop; end; end; ' \
              's=Stack.new; s.push(1).push(2).push(3); puts s.pop',
              '3', 'method chaining'

      # ── Modules ───────────────────────────────────────────────────────
      mr.call 'module Greetable; def greet; "Hi from #{self.class}"; end; end; ' \
              'class Person; include Greetable; end; puts Person.new.greet',
              'Hi from Person', 'module include'
      mr.call 'module MathExt; def double; self * 2; end; end; ' \
              'class Integer; include MathExt; end; puts 21.double',
              '42', 'open class with module'

      # ── Blocks, procs, and lambdas ────────────────────────────────────
      mr.call 'sq=->(x){x*x}; puts [1,2,3,4].map(&sq).inspect', '[1, 4, 9, 16]'
      mr.call 'def apply(x); yield x; end; puts apply(5){|n| n*3}', '15'
      mr.call 'adder=->(n){->(x){x+n}}; add5=adder.(5); puts add5.(10)', '15'
      mr.call 'def count; [1,2,3].each{|n| yield n}; end; s=0; count{|n| s+=n}; puts s', '6'

      # ── Symbols ───────────────────────────────────────────────────────
      mr.call 'puts :hello.to_s',                           'hello'
      mr.call 'puts "world".to_sym.inspect',                ':world'
      mr.call 'puts [:a,:b,:c].map(&:to_s).inspect',       '["a", "b", "c"]'
      mr.call 'puts [:foo,:bar,:baz].sort.first.inspect',   ':bar'

      # ── Exceptions ────────────────────────────────────────────────────
      mr.call 'begin; raise "oops"; rescue => e; puts e.message; end', 'oops'
      mr.call 'begin; 1/0; rescue ZeroDivisionError; puts "caught"; end', 'caught'
      mr.call 'result=begin; 42; ensure; 99; end; puts result', '42'
      mr.call 'begin; raise "x"; rescue => e; puts e.class; end', 'RuntimeError'

      # ── Enumerable extras ─────────────────────────────────────────────
      mr.call 'puts [5,2,8,1,9].min',                  '1'
      mr.call 'puts [5,2,8,1,9].max',                  '9'
      mr.call 'puts [1,2,3,4].each_slice(2).to_a.inspect', '[[1, 2], [3, 4]]'
      mr.call 'puts [1,2,3,4].each_cons(2).to_a.inspect',  '[[1, 2], [2, 3], [3, 4]]'
      mr.call 'puts (1..5).reduce{|acc,n| acc*n}',     '120'
      mr.call 'puts ["a","bb","ccc"].sort_by(&:length).inspect', '["a", "bb", "ccc"]'
      mr.call 'puts [1,2,3].flat_map{|n| [n,-n]}.inspect', '[1, -1, 2, -2, 3, -3]'
    ensure
      puts "Build dir kept at: #{build_dir}"
    end
  end
end
