# frozen_string_literal: true

require 'open3'
require 'fileutils'

# Phase 11 Tier 4: CRuby 3.4 (miniruby)
#
# Compiles the CRuby interpreter using occ and verifies that the resulting
# miniruby binary can execute basic Ruby programs.
#
# Prerequisites (Phase 13 — GCC Extension Compatibility):
#   - Statement expressions ({ ... })
#   - __typeof__ with correct type reflection
#   - __builtin_offsetof computing correct offsets
#   - Alternate keyword spellings (__inline__, __volatile__, __asm__, etc.)
#   - __extension__ as a no-op keyword
#   - __builtin_clz / __builtin_ctz / __builtin_popcount
#   - Inline assembly (asm volatile("" ::: "memory"))
#
# Build strategy:
#   1. Clone ruby/ruby at a known tag
#   2. Run ./autogen.sh + ./configure using the system toolchain to generate
#      config.h, ruby/config.h, and other autoconf artefacts (occ is not used
#      for this step — configure requires a fully working C compiler)
#   3. Compile each miniruby source file to a .o with occ
#   4. Link all objects into miniruby using clang
#   5. Run smoke tests
#
# Run with:
#   THIRDPARTY=1 bundle exec rspec spec/phase11/ruby_spec.rb

RSpec.describe 'Phase 11: CRuby 3.4 miniruby (Tier 4)', :thirdparty do
  include ThirdpartyHelper

  RUBY_TAG    = 'v3_4_0'
  RUBY_REPO   = 'https://github.com/ruby/ruby.git'
  RUBY_CACHE  = File.join(ThirdpartyHelper::CACHE_DIR, 'ruby')

  # Core Ruby source files (NORMALMAINOBJ + COMMONOBJS + MINIOBJS) that form
  # miniruby. Generated by inspecting `make minirubymain` with Ruby v3_4_0.
  # vm_exec.c and vm_method.c are #include'd by vm.c — do not compile separately.
  MINIRUBY_SOURCES = %w[
    main.c
    array.c
    ast.c
    bignum.c
    class.c
    compar.c
    compile.c
    complex.c
    cont.c
    debug.c
    debug_counter.c
    dir.c
    dln_find.c
    dmydln.c
    encoding.c
    enum.c
    enumerator.c
    error.c
    eval.c
    file.c
    gc.c
    hash.c
    imemo.c
    inits.c
    io.c
    io_buffer.c
    iseq.c
    load.c
    marshal.c
    math.c
    memory_view.c
    miniinit.c
    node.c
    node_dump.c
    numeric.c
    object.c
    pack.c
    parse.c
    parser_st.c
    proc.c
    process.c
    ractor.c
    random.c
    range.c
    rational.c
    re.c
    regcomp.c
    regenc.c
    regerror.c
    regexec.c
    regparse.c
    regsyntax.c
    rjit.c
    rjit_c.c
    ruby.c
    ruby_exts.c
    ruby_parser.c
    scheduler.c
    shape.c
    signal.c
    sprintf.c
    st.c
    strftime.c
    string.c
    struct.c
    symbol.c
    thread.c
    time.c
    transcode.c
    util.c
    variable.c
    version.c
    vm.c
    vm_backtrace.c
    vm_dump.c
    vm_sync.c
    vm_trace.c
    weakmap.c
    addr2line.c
    missing/explicit_bzero.c
    missing/setproctitle.c
  ].freeze

  # Prism sources (Ruby 3.4 uses Prism as the default parser).
  # Includes both static and template-generated sources.
  PRISM_SOURCES = %w[
    prism/prism.c
    prism/api_pack.c
    prism/diagnostic.c
    prism/encoding.c
    prism/node.c
    prism/options.c
    prism/pack.c
    prism/prettyprint.c
    prism/regexp.c
    prism/serialize.c
    prism/static_literals.c
    prism/token_type.c
    prism/util/pm_buffer.c
    prism/util/pm_char.c
    prism/util/pm_constant_pool.c
    prism/util/pm_integer.c
    prism/util/pm_list.c
    prism/util/pm_memchr.c
    prism/util/pm_newline_list.c
    prism/util/pm_string.c
    prism/util/pm_strncasecmp.c
    prism/util/pm_strpbrk.c
    prism/extension.c
    prism/api_node.c
    prism_init.c
  ].freeze

  # Built-in encoding and transcoder objects (BUILTIN_ENCOBJS + BUILTIN_TRANSOBJS).
  ENC_SOURCES = %w[
    enc/ascii.c
    enc/us_ascii.c
    enc/unicode.c
    enc/utf_8.c
    enc/utf_16be.c
    enc/utf_16le.c
    enc/utf_32be.c
    enc/utf_32le.c
    enc/euc_jp.c
    enc/windows_31j.c
    enc/shift_jis.c
    enc/encdb.c
    enc/trans/newline.c
    enc/trans/japanese_euc.c
    enc/trans/japanese_sjis.c
    enc/trans/japanese.c
    enc/trans/utf_16_32.c
    enc/trans/iso2022.c
  ].freeze

  # Transcoder .c files that are generated from .trans sources and need
  # their Init functions called from Init_ext() in miniinit.c.
  TRANS_INITS = %w[japanese_euc japanese_sjis japanese utf_16_32 iso2022].freeze

  # ── Full ruby extensions ──────────────────────────────────────────────────

  LIBYAML_REPO = 'https://github.com/yaml/libyaml.git'
  LIBYAML_TAG  = '0.2.5'

  # Extensions that compile without running extconf.rb, paired with their Init
  # function name (nil = source file has no top-level Init of its own).
  RUBY_EXT_SOURCES = {
    'ext/stringio/stringio.c'                => 'Init_stringio',
    'ext/strscan/strscan.c'                  => 'Init_strscan',
    'ext/date/date_core.c'                   => 'Init_date_core',
    'ext/date/date_parse.c'                  => nil,
    'ext/date/date_strptime.c'               => nil,
    'ext/date/date_strftime.c'               => nil,
    'ext/zlib/zlib.c'                        => 'Init_zlib',
    'ext/digest/digest.c'                    => 'Init_digest',
    'ext/digest/bubblebabble/bubblebabble.c' => 'Init_bubblebabble',
    'ext/digest/md5/md5.c'                   => nil,
    'ext/digest/md5/md5init.c'               => 'Init_md5',
    'ext/digest/sha1/sha1.c'                 => nil,
    'ext/digest/sha1/sha1init.c'             => 'Init_sha1',
    'ext/digest/sha2/sha2.c'                 => nil,
    'ext/digest/sha2/sha2init.c'             => 'Init_sha2',
    'ext/digest/rmd160/rmd160.c'             => nil,
    'ext/digest/rmd160/rmd160init.c'         => 'Init_rmd160',
    'ext/continuation/continuation.c'        => 'Init_continuation',
    'ext/fcntl/fcntl.c'                      => 'Init_fcntl',
    'ext/pathname/pathname.c'                => 'Init_pathname',
    'ext/coverage/coverage.c'                => 'Init_coverage',
    'ext/monitor/monitor.c'                  => 'Init_monitor',
    'ext/pty/pty.c'                          => 'Init_pty',
    'ext/objspace/objspace.c'                => 'Init_objspace',
    'ext/objspace/object_tracing.c'          => nil,
    'ext/objspace/objspace_dump.c'           => nil,
    'ext/json/parser/parser.c'               => 'Init_parser',
    'ext/json/generator/generator.c'         => 'Init_generator',
  }.freeze

  # io/console needs POSIX terminal defines that extconf.rb probes on macOS.
  IO_CONSOLE_DEFINES = %w[-DHAVE_TERMIOS_H -DHAVE_RB_IO_DESCRIPTOR -DHAVE_RB_IO_PATH].freeze

  # psych (YAML): source files relative to build_dir, plus init name.
  PSYCH_SOURCES = {
    'ext/psych/psych.c'            => 'Init_psych',
    'ext/psych/psych_parser.c'     => nil,
    'ext/psych/psych_emitter.c'    => nil,
    'ext/psych/psych_to_ruby.c'    => nil,
    'ext/psych/psych_yaml_tree.c'  => nil,
  }.freeze

  # fiddle (FFI): source files relative to build_dir, plus init name.
  FIDDLE_SOURCES = {
    'ext/fiddle/fiddle.c'          => 'Init_fiddle',
    'ext/fiddle/closure.c'         => nil,
    'ext/fiddle/conversions.c'     => nil,
    'ext/fiddle/function.c'        => nil,
    'ext/fiddle/handle.c'          => nil,
    'ext/fiddle/memory_view.c'     => nil,
    'ext/fiddle/pinned.c'          => nil,
    'ext/fiddle/pointer.c'         => nil,
  }.freeze

  # openssl: all .c files in ext/openssl, need extconf.h generated first.
  OPENSSL_INIT = 'Init_openssl'

  # Returns the install prefix for libyaml (include/yaml.h lives there).
  # Checks Homebrew locations first, then clones and builds from source.
  def find_or_build_libyaml
    homebrew_prefixes = %w[/opt/homebrew/opt/libyaml /usr/local/opt/libyaml]
    homebrew = homebrew_prefixes.find { |d| File.exist?("#{d}/include/yaml.h") }
    return homebrew if homebrew

    src_dir     = git_clone(LIBYAML_REPO, LIBYAML_TAG, 'libyaml')
    install_dir = File.join(ThirdpartyHelper::CACHE_DIR, 'libyaml_install')
    return install_dir if File.exist?("#{install_dir}/include/yaml.h")

    build_tmp = Dir.mktmpdir('occ_libyaml_')
    begin
      FileUtils.cp_r(Dir["#{src_dir}/*"], build_tmp)
      system('bash autogen.sh > /dev/null 2>&1', chdir: build_tmp)
      system("./configure --disable-shared --enable-static --prefix=#{install_dir} > /dev/null 2>&1",
             chdir: build_tmp)
      system('make > /dev/null 2>&1', chdir: build_tmp)
      system('make install > /dev/null 2>&1', chdir: build_tmp)
    ensure
      FileUtils.rm_rf(build_tmp)
    end

    File.exist?("#{install_dir}/include/yaml.h") ? install_dir : nil
  end

  def autotools_available?
    system('which autoconf > /dev/null 2>&1') &&
      system('which ./configure > /dev/null 2>&1 || true')
  end

  def run_configure(build_dir)
    # autogen.sh generates ./configure from configure.ac
    unless system('bash autogen.sh > /dev/null 2>&1', chdir: build_dir)
      skip 'ruby autogen.sh failed — autoconf may not be installed'
    end

    # Run configure with system clang to produce config.h and friends.
    # --disable-rubygems and --without-* keep the build minimal.
    configure_flags = %w[
      --disable-rubygems
      --disable-install-doc
      --without-gmp
      --with-static-linked-ext
    ]
    _out, err, st = Open3.capture3(
      './configure', *configure_flags,
      chdir: build_dir
    )
    unless st.success?
      skip "ruby ./configure failed:\n#{err.slice(0, 500)}"
    end
  end

  def disable_unsupported_config(build_dir)
    config_paths = [
      File.join(build_dir, 'include', 'ruby', 'internal', 'config.h'),
      *Dir.glob(File.join(build_dir, '.ext', 'include', '*', 'ruby', 'config.h')),
      *Dir.glob(File.join(build_dir, '**', 'config.h')),
    ].uniq

    config_paths.each do |path|
      next unless File.file?(path)

      text = File.read(path)
      next unless text.include?('USE_RJIT')

      text = text.gsub(/^#define USE_RJIT\b.*$/, '#define USE_RJIT 0')
      File.write(path, text)
    end
  end

  it 'compiles miniruby and runs basic scripts', :slow do
    require_git!
    skip 'autoconf not available' unless system('which autoconf > /dev/null 2>&1')

    # ── 1. Clone source ────────────────────────────────────────────────────
    src_dir = git_clone(RUBY_REPO, RUBY_TAG, 'ruby')

    build_dir = Dir.mktmpdir('occ_ruby_')
    begin
      # Copy source into build dir so configure can write files there
      FileUtils.cp_r(Dir["#{src_dir}/*"], build_dir)
      FileUtils.cp_r(Dir["#{src_dir}/.[^.]*"].select { |f| File.file?(f) }, build_dir)

      # ── 2. Run ./configure with system toolchain ───────────────────────
      run_configure(build_dir)
      # OCC has full 128-bit integer support (two adjacent 8-byte slots, real
      # mul+umulh), so HAVE_INT128_T is left enabled. USE_RJIT is forced off
      # because the JIT shim reads iseq on C frames (iseq==NULL crash).
      disable_unsupported_config(build_dir)

      # ── 3. Generate parser and other generated files via make ─────────
      # parse.c/lex.c from parse.y; id.h/id.c; probes.h; insns_info.inc/node_name.inc from tools
      system('make parse.c lex.c id.h id.c probes.h known_errors.inc insns.inc insns_info.inc optinsn.inc optunifs.inc vmtc.inc vm.inc node_name.inc vm_call_iseq_optimized.inc encdb.h enc/jis/props.h BASERUBY=ruby 2>/dev/null',
             chdir: build_dir)

      # Generate prism template-derived headers (diagnostic.h, ast.h).
      # These are template-generated and not built by default until 'srcs' target
      # runs, but prism utility headers include them directly.
      %w[include/prism/diagnostic.h include/prism/ast.h].each do |tmpl_name|
        out_path = File.join(build_dir, 'prism', File.basename(tmpl_name))
        next if File.exist?(out_path)
        system("ruby prism/templates/template.rb #{tmpl_name} #{out_path} 2>/dev/null",
               chdir: build_dir)
      end

      # Generate prism template-derived C source files.
      {
        'src/diagnostic.c'      => 'prism/diagnostic.c',
        'src/node.c'            => 'prism/node.c',
        'src/prettyprint.c'     => 'prism/prettyprint.c',
        'src/serialize.c'       => 'prism/serialize.c',
        'src/token_type.c'      => 'prism/token_type.c',
        'ext/prism/api_node.c'  => 'prism/api_node.c',
      }.each do |tmpl_name, out_name|
        out_path = File.join(build_dir, out_name)
        next if File.exist?(out_path)
        system("ruby prism/templates/template.rb #{tmpl_name} #{out_path} 2>/dev/null",
               chdir: build_dir)
      end

      # Generate enc/trans/newline.c and other transcoder .c files from .trans sources.
      FileUtils.mkdir_p(File.join(build_dir, 'enc/trans'))
      (%w[newline] + TRANS_INITS).each do |name|
        out_c = File.join(build_dir, "enc/trans/#{name}.c")
        unless File.exist?(out_c)
          system("ruby tool/transcode-tblgen.rb -vo #{out_c} enc/trans/#{name}.trans 2>/dev/null",
                 chdir: build_dir)
        end
      end

      # Generate miniprelude.c (included by mini_builtin.c which is included by miniinit.c).
      # Requires rbinc targets to be up to date first.
      rbinc_targets = (MINIRUBY_SOURCES + %w[warning.c]).filter_map do |s|
        rb = s.sub('.c', '.rb')
        File.exist?(File.join(build_dir, rb)) ? rb.sub('.rb', '.rbinc') : nil
      end
      extra_rbincs = %w[kernel.rbinc nilclass.rbinc timev.rbinc trace_point.rbinc thread_sync.rbinc yjit_hook.rbinc prelude.rbinc gem_prelude.rbinc yjit.rbinc].select do |r|
        File.exist?(File.join(build_dir, r.sub('.rbinc', '.rb')))
      end
      rbinc_targets = (rbinc_targets + extra_rbincs).uniq
      system("make -k #{rbinc_targets.join(' ')} BASERUBY=ruby 2>/dev/null",
             chdir: build_dir) if rbinc_targets.any?

      miniprelude_c = File.join(build_dir, 'miniprelude.c')
      unless File.exist?(miniprelude_c)
        system('make miniprelude.c BASERUBY=ruby 2>/dev/null', chdir: build_dir)
      end

      # Patch miniinit.c so:
      # 1. Init_enc() calls Init_encdb() and the built-in encoding Init functions,
      #    making Encoding::UTF_16BE etc. available without duplicate warnings.
      # 2. Init_ext() calls Init functions for statically-linked transcoders so that
      #    String#encode can find converters like UTF-8→EUC-JP and UTF-8→UTF-16.
      #
      # Each patch is guarded independently so re-running on a cached build dir
      # only applies the patches that are still missing.
      miniinit_path = File.join(build_dir, 'miniinit.c')
      if File.exist?(miniinit_path)
        src = File.read(miniinit_path)

        # Patch 1: Init_enc() — encoding registrations.
        unless src.include?('Init_encdb')
          enc_funcs = %w[utf_16be utf_16le utf_32be utf_32le euc_jp windows_31j shift_jis]
          decl_lines = (enc_funcs.map { |f| "void Init_#{f}(void);" } + ['void Init_encdb(void);']).join("\n")
          # Call Init_encdb first so dynamic encodings (Shift_JIS etc.) are registered as
          # zeroed stubs before the Init_XXX calls fill in their implementations in-place.
          call_lines = (['    Init_encdb();'] + enc_funcs.map { |f| "    Init_#{f}();" }).join("\n")
          src = src
            .sub("void rb_encdb_declare(const char *name);\nint rb_encdb_alias(const char *alias, const char *orig);\nvoid\nInit_enc(void)\n{",
                 "#{decl_lines}\nvoid rb_encdb_declare(const char *name);\nint rb_encdb_alias(const char *alias, const char *orig);\nvoid\nInit_enc(void)\n{")
            .sub("    rb_encdb_declare(\"ASCII-8BIT\");\n    rb_encdb_declare(\"US-ASCII\");\n    rb_encdb_declare(\"UTF-8\");\n    rb_encdb_alias(\"BINARY\", \"ASCII-8BIT\");\n    rb_encdb_alias(\"ASCII\", \"US-ASCII\");\n}",
                 "#{call_lines}\n}")
        end

        # Patch 2: Init_ext() — statically-linked transcoder Init calls.
        # EXTSTATIC=1 is set in ruby/config.h (from --with-static-linked-ext),
        # so TRANS_INIT(name) expands to Init_trans_NAME rather than Init_NAME.
        # Use gsub with regex so re-patching works as TRANS_INITS grows.
        unless src.include?('Init_trans_iso2022')
          trans_decls = TRANS_INITS.map { |f| "void Init_trans_#{f}(void);" }.join("\n")
          trans_calls = TRANS_INITS.map { |f| "    Init_trans_#{f}();" }.join("\n")
          src = src.gsub(
            /(?:void Init_trans_\w+\(void\);\n)*\/\* miniruby does not support dynamic loading\. \*\/\nvoid\nInit_ext\(void\)\n\{[^}]*\}/m,
            "#{trans_decls}\n/* miniruby does not support dynamic loading. */\nvoid\nInit_ext(void)\n{\n#{trans_calls}\n}"
          )
        end

        File.write(miniinit_path, src)
      end

      # Collect include paths that configure produces.
      # The platform-specific ext dir uses the Darwin kernel version (e.g. arm64-darwin25),
      # so glob for it rather than hard-coding the version number.
      ext_include_dir = Dir.glob("#{build_dir}/.ext/include/arm64-darwin*/").first ||
                        Dir.glob("#{build_dir}/.ext/include/*/").first
      unicode_hdr_dir = Dir.glob("#{build_dir}/enc/unicode/*/").first
      include_flags = [
        "-I#{build_dir}",
        "-I#{build_dir}/include",
        "-I#{build_dir}/prism",
        (ext_include_dir ? "-I#{ext_include_dir.chomp('/')}" : nil),
        (unicode_hdr_dir ? "-I#{unicode_hdr_dir.chomp('/')}" : nil),
      ].compact.select { |f| Dir.exist?(f.sub(/^-I/, '')) }
      include_flags += ['-I', ThirdpartyHelper::SDK_INCLUDE] if ThirdpartyHelper::SDK_INCLUDE

      # Add macOS framework search path so <Framework/Header.h> includes resolve
      sdk_path = `xcrun --show-sdk-path 2>/dev/null`.strip
      framework_flags = sdk_path.empty? ? [] : ['-F', File.join(sdk_path, 'System', 'Library', 'Frameworks')]

      base_compile_flags = include_flags + framework_flags + [
        '-c', '-DRUBY_EXPORT', '-DMINIRUBY',
        '-DDTRACE_PROBES_DISABLED=1',
        '-DOPT_THREADED_CODE=3',
        '-D_XOPEN_SOURCE',
      ]

      # ── 4. Compile each miniruby source file with occ ──────────────────
      obj_files = []
      compile_errors = []

      # These enc files use OnigEncodingDefine which generates Init_XXX via ONIG_ENC_REGISTER.
      enc_with_init = %w[utf_16be utf_16le utf_32be utf_32le euc_jp windows_31j shift_jis]
        .map { |f| "enc/#{f}.c" }.to_set

      all_sources = MINIRUBY_SOURCES + PRISM_SOURCES + ENC_SOURCES

      all_sources.each do |src_name|
        src_path = File.join(build_dir, src_name)
        next unless File.exist?(src_path)

        obj_name = src_name.sub('.c', '.o')
        obj_path = File.join(build_dir, obj_name)
        FileUtils.mkdir_p(File.dirname(obj_path))

        flags = base_compile_flags
        flags = flags + ['-DONIG_ENC_REGISTER=rb_enc_register'] if enc_with_init.include?(src_name)

        result = occ_compile(
          src_path,
          output: obj_path,
          flags: flags
        )

        if result[:status] == 0
          obj_files << obj_path
        else
          compile_errors << "#{src_name}: #{result[:stderr].lines.first&.strip}"
        end
      end

      # ── 5. Compile ARM64 coroutine implementation (assembly) with clang ──
      coroutine_s = File.join(build_dir, 'coroutine/arm64/Context.S')
      if File.exist?(coroutine_s)
        coroutine_o = File.join(build_dir, 'coroutine/arm64/Context.o')
        FileUtils.mkdir_p(File.dirname(coroutine_o))
        if system("clang -c #{coroutine_s} -I#{build_dir} '-DPREFIXED_SYMBOL(name)=TOKEN_PASTE(_,name)' -o #{coroutine_o} 2>/dev/null")
          obj_files << coroutine_o
        end
      end

      expect(obj_files).not_to be_empty, 'no object files were produced'

      # Report compile errors but don't fail immediately — show progress
      if compile_errors.any?
        fail "#{compile_errors.length} file(s) failed to compile:\n" \
             "#{compile_errors.first(10).join("\n")}"
      end

      # ── 6. Link miniruby with clang ────────────────────────────────────
      miniruby_bin = File.join(build_dir, 'miniruby')
      _, link_err, link_st = Open3.capture3(
        'clang', *obj_files, '-o', miniruby_bin,
        '-lpthread', '-ldl', '-lm', '-liconv',
        '-framework', 'CoreFoundation'
      )
      expect(link_st.exitstatus).to eq(0),
        "link failed:\n#{link_err.slice(0, 5000)}"

      # ── 7. Smoke tests ────────────────────────────────────────────────
      # Helper: run a one-liner in miniruby, check exit status and stdout.
      miniruby_env = {
        'RUBYOPT' => nil,
        'RUBYLIB' => nil,
        'GEM_HOME' => nil,
        'GEM_PATH' => nil,
        'BUNDLE_BIN_PATH' => nil,
        'BUNDLE_GEMFILE' => nil,
        'BUNDLER_ORIG_BUNDLE_BIN_PATH' => nil,
        'BUNDLER_ORIG_BUNDLE_GEMFILE' => nil,
        'BUNDLER_ORIG_GEM_HOME' => nil,
        'BUNDLER_ORIG_GEM_PATH' => nil,
        'BUNDLER_ORIG_MANPATH' => nil,
        'BUNDLER_ORIG_PATH' => nil,
        'BUNDLER_ORIG_RB_USER_INSTALL' => nil,
        'BUNDLER_ORIG_RUBYLIB' => nil,
        'BUNDLER_ORIG_RUBYOPT' => nil,
      }
      mr = ->(code, expected, label = nil) {
        label ||= code.length > 60 ? "#{code[0, 57]}..." : code
        out, err, st = Open3.capture3(miniruby_env, miniruby_bin, '-e', code)
        expect(st.exitstatus).to eq(0),
          "#{label}: non-zero exit (binary: #{miniruby_bin})\n#{err.slice(0, 2000)}"
        expect(out.strip).to eq(expected.strip), label
      }

      # ── Integers and arithmetic ───────────────────────────────────────
      mr.call 'puts 1 + 1',                   '2'
      mr.call 'puts 2 ** 10',                 '1024'
      mr.call 'puts 17 % 5',                  '2'
      mr.call 'puts -7.divmod(3).inspect',    '[-3, 2]'
      mr.call 'puts 255.to_s(16)',             'ff'
      mr.call 'puts 0xff',                     '255'
      mr.call 'puts 10.gcd(6)',                '2'
      mr.call 'puts 5.lcm(6)',                 '30'

      # ── Floats and Math ───────────────────────────────────────────────
      mr.call 'puts (0.1 + 0.2).round(1)',     '0.3'
      mr.call 'puts Math.sqrt(144).to_i',      '12'
      mr.call 'puts 3.14.ceil',                '4'
      mr.call 'puts (-3.7).floor',             '-4'

      # ── Strings ───────────────────────────────────────────────────────
      mr.call 'puts "hello from occ"',         'hello from occ'
      mr.call 'puts "hello".upcase',            'HELLO'
      mr.call 'puts "WORLD".downcase',          'world'
      mr.call 'puts "hello world".split.length', '2'
      mr.call 'puts "abc" * 3',                 'abcabcabc'
      mr.call 'n = 42; puts "n=#{n}"',          'n=42'
      mr.call 'puts "hello".chars.sort.join',   'ehllo'
      mr.call 'puts "   trim   ".strip',        'trim'
      mr.call 'puts "hello world".gsub("l","L")', 'heLLo worLd'
      mr.call 'puts "hello"[1..3]',             'ell'
      mr.call 'puts "hello".start_with?("hel")', 'true'
      mr.call 'puts "a,b,c".split(",").inspect', '["a", "b", "c"]'
      mr.call 'puts "%05d" % 42',              '00042'

      # ── Arrays ────────────────────────────────────────────────────────
      mr.call 'puts [1,2,3].map{|x| x*x}.inspect', '[1, 4, 9]'
      mr.call 'puts [3,1,2].sort.inspect',          '[1, 2, 3]'
      mr.call 'puts [1,2,3,4,5].select(&:odd?).inspect', '[1, 3, 5]'
      mr.call 'puts [1,2,3,4,5].reject(&:even?).inspect', '[1, 3, 5]'
      mr.call 'puts [1,2,3].inject(:+)',             '6'
      mr.call 'puts [1,2,3,4,5].sum',                '15'
      mr.call 'puts [[1,2],[3,[4]]].flatten.inspect', '[1, 2, 3, 4]'
      mr.call 'puts [1,2,2,3].uniq.inspect',         '[1, 2, 3]'
      mr.call 'a = [1,2,3]; a.push(4); puts a.pop',  '4'
      mr.call 'puts [1,2,3].zip([4,5,6]).map{|a,b| a+b}.inspect', '[5, 7, 9]'
      mr.call 'puts [3,1,4,1,5].sort.first(3).inspect', '[1, 1, 3]'

      # ── Hashes ────────────────────────────────────────────────────────
      mr.call 'h={a:1,b:2,c:3}; puts h[:b]',             '2'
      mr.call 'h={a:1,b:2}; puts h.values.sort.inspect',  '[1, 2]'
      mr.call 'h={a:1,b:2}; puts h.map{|k,v| v*2}.sort.inspect', '[2, 4]'
      mr.call 'h={}; h[:x]=10; h[:y]=20; puts h.values.sum', '30'
      mr.call 'puts({a:1,b:2,c:3}.any?{|k,v| v>2})',      'true'
      mr.call 'puts({a:1,b:2,c:3}.count{|k,v| v.odd?})',   '2'

      # ── Ranges ────────────────────────────────────────────────────────
      mr.call 'puts (1..5).to_a.inspect',               '[1, 2, 3, 4, 5]'
      mr.call 'puts (1...5).to_a.inspect',              '[1, 2, 3, 4]'
      mr.call 'puts (1..10).select{|n| n.even?}.inspect', '[2, 4, 6, 8, 10]'
      mr.call 'puts (1..100).select{|n| n%15==0}.inspect', '[15, 30, 45, 60, 75, 90]'
      mr.call 'puts (1..5).include?(3)',                'true'

      # ── Control flow ──────────────────────────────────────────────────
      mr.call 'x=10; puts x>5 ? "big" : "small"',     'big'
      mr.call 'i=0; while i<5; i+=1; end; puts i',    '5'
      mr.call 'i=3; until i==0; i-=1; end; puts i',   '0'
      mr.call 'puts case 7; when 1..5 then "low"; when 6..10 then "mid"; else "high"; end', 'mid'
      mr.call '3.times{|i| print i}; puts',            '012'
      mr.call 'puts 5.downto(1).to_a.inspect',         '[5, 4, 3, 2, 1]'

      # ── Methods ───────────────────────────────────────────────────────
      mr.call 'def fact(n); n<=1 ? 1 : n*fact(n-1); end; puts fact(10)', '3628800'
      mr.call 'def hi(name="world"); "Hello, #{name}!"; end; puts hi; puts hi("Ruby")',
              "Hello, world!\nHello, Ruby!"
      mr.call 'def sum(*args); args.sum; end; puts sum(1,2,3,4,5)',    '15'
      mr.call 'def fib(n); n<2 ? n : fib(n-1)+fib(n-2); end; puts (0..7).map{|i| fib(i)}.inspect',
              '[0, 1, 1, 2, 3, 5, 8, 13]'

      # ── Classes ───────────────────────────────────────────────────────
      mr.call 'class Rect; def initialize(w,h); @w,@h=w,h; end; ' \
              'def area; @w*@h; end; end; puts Rect.new(3,4).area',
              '12', 'class with initialize'
      mr.call 'class Counter; def initialize; @n=0; end; ' \
              'def inc; @n+=1; end; def val; @n; end; end; ' \
              'c=Counter.new; 5.times{c.inc}; puts c.val',
              '5', 'stateful class'
      mr.call 'class Animal; def speak; "..."; end; end; ' \
              'class Dog < Animal; def speak; "Woof"; end; end; ' \
              'puts Dog.new.speak; puts Dog.new.is_a?(Animal)',
              "Woof\ntrue", 'inheritance'
      mr.call 'class Stack; def initialize; @s=[]; end; ' \
              'def push(v); @s<<v; self; end; def pop; @s.pop; end; end; ' \
              's=Stack.new; s.push(1).push(2).push(3); puts s.pop',
              '3', 'method chaining'

      # ── Modules ───────────────────────────────────────────────────────
      mr.call 'module Greetable; def greet; "Hi from #{self.class}"; end; end; ' \
              'class Person; include Greetable; end; puts Person.new.greet',
              'Hi from Person', 'module include'
      mr.call 'module MathExt; def double; self * 2; end; end; ' \
              'class Integer; include MathExt; end; puts 21.double',
              '42', 'open class with module'

      # ── Blocks, procs, and lambdas ────────────────────────────────────
      mr.call 'sq=->(x){x*x}; puts [1,2,3,4].map(&sq).inspect', '[1, 4, 9, 16]'
      mr.call 'def apply(x); yield x; end; puts apply(5){|n| n*3}', '15'
      mr.call 'adder=->(n){->(x){x+n}}; add5=adder.(5); puts add5.(10)', '15'
      mr.call 'def count; [1,2,3].each{|n| yield n}; end; s=0; count{|n| s+=n}; puts s', '6'

      # ── Symbols ───────────────────────────────────────────────────────
      mr.call 'puts :hello.to_s',                           'hello'
      mr.call 'puts "world".to_sym.inspect',                ':world'
      mr.call 'puts [:a,:b,:c].map(&:to_s).inspect',       '["a", "b", "c"]'
      mr.call 'puts [:foo,:bar,:baz].sort.first.inspect',   ':bar'

      # ── Exceptions ────────────────────────────────────────────────────
      mr.call 'begin; raise "oops"; rescue => e; puts e.message; end', 'oops'
      mr.call 'begin; 1/0; rescue ZeroDivisionError; puts "caught"; end', 'caught'
      mr.call 'result=begin; 42; ensure; 99; end; puts result', '42'
      mr.call 'begin; raise "x"; rescue => e; puts e.class; end', 'RuntimeError'

      # ── Enumerable extras ─────────────────────────────────────────────
      mr.call 'puts [5,2,8,1,9].min',                  '1'
      mr.call 'puts [5,2,8,1,9].max',                  '9'
      mr.call 'puts [1,2,3,4].each_slice(2).to_a.inspect', '[[1, 2], [3, 4]]'
      mr.call 'puts [1,2,3,4].each_cons(2).to_a.inspect',  '[[1, 2], [2, 3], [3, 4]]'
      mr.call 'puts (1..5).reduce{|acc,n| acc*n}',     '120'
      mr.call 'puts ["a","bb","ccc"].sort_by(&:length).inspect', '["a", "bb", "ccc"]'
      mr.call 'puts [1,2,3].flat_map{|n| [n,-n]}.inspect', '[1, -1, 2, -2, 3, -3]'

      # ── 8. Resolve external library dependencies ───────────────────────
      libyaml_prefix = find_or_build_libyaml

      openssl_prefix = %w[
        /opt/homebrew/opt/openssl@3
        /opt/homebrew/opt/openssl
        /usr/local/opt/openssl@3
        /usr/local/opt/openssl
      ].find { |d| File.exist?("#{d}/include/openssl/ssl.h") }

      ffi_include = sdk_path.empty? ? nil : "#{sdk_path}/usr/include/ffi"
      ffi_include = nil unless ffi_include && Dir.exist?(ffi_include)

      # Extension-compile flags: same as base but without -DMINIRUBY,
      # with -DEXTSTATIC so Init_* symbols are emitted unconditionally.
      ext_base_flags = include_flags + framework_flags + [
        '-c', '-DRUBY_EXPORT', '-DEXTSTATIC=1',
        '-DDTRACE_PROBES_DISABLED=1',
        '-DOPT_THREADED_CODE=3',
        '-D_XOPEN_SOURCE',
      ]

      # ── 9. Compile C extensions with occ ──────────────────────────────
      ext_obj_files   = []
      ext_inits       = []
      ext_errs        = []

      compile_ext = lambda do |src_path, init_name, extra_flags: []|
        obj_path = src_path.sub('.c', '.o')
        FileUtils.mkdir_p(File.dirname(obj_path))
        r = occ_compile(src_path, output: obj_path, flags: ext_base_flags + extra_flags)
        if r[:status] == 0
          ext_obj_files << obj_path
          ext_inits << init_name if init_name
        else
          rel = src_path.sub("#{build_dir}/", '')
          ext_errs << "#{rel}: #{r[:stderr].lines.first&.strip}"
        end
      end

      # Core extensions
      RUBY_EXT_SOURCES.each do |src_name, init_name|
        src_path = File.join(build_dir, src_name)
        next unless File.exist?(src_path)
        compile_ext.call(src_path, init_name,
                         extra_flags: ["-I#{File.dirname(src_path)}"])
      end

      # io/console
      console_src = File.join(build_dir, 'ext/io/console/console.c')
      if File.exist?(console_src)
        compile_ext.call(console_src, 'Init_console',
                         extra_flags: IO_CONSOLE_DEFINES + ["-I#{File.join(build_dir, 'ext/io/console')}"])
      end

      # psych (libyaml)
      if libyaml_prefix
        PSYCH_SOURCES.each do |src_name, init_name|
          src_path = File.join(build_dir, src_name)
          next unless File.exist?(src_path)
          compile_ext.call(src_path, init_name,
                           extra_flags: [
                             "-I#{File.join(build_dir, 'ext/psych')}",
                             "-I#{libyaml_prefix}/include",
                           ])
        end
      end

      # fiddle (libffi from SDK)
      if ffi_include
        FIDDLE_SOURCES.each do |src_name, init_name|
          src_path = File.join(build_dir, src_name)
          next unless File.exist?(src_path)
          compile_ext.call(src_path, init_name,
                           extra_flags: [
                             "-I#{File.join(build_dir, 'ext/fiddle')}",
                             "-I#{ffi_include}",
                           ])
        end
      end

      # openssl
      if openssl_prefix
        ossl_dir = File.join(build_dir, 'ext/openssl')
        unless File.exist?("#{ossl_dir}/extconf.h")
          system('ruby extconf.rb 2>/dev/null', chdir: ossl_dir)
        end
        if File.exist?("#{ossl_dir}/extconf.h")
          Dir.glob("#{ossl_dir}/*.c").sort.each do |src_path|
            compile_ext.call(src_path, nil,
                             extra_flags: [
                               "-I#{ossl_dir}",
                               "-I#{openssl_prefix}/include",
                               '-DRUBY_EXTCONF_H="extconf.h"',
                             ])
          end
          ext_inits << OPENSSL_INIT
        end
      end

      # Report any extension compile failures
      if ext_errs.any?
        fail "#{ext_errs.length} extension file(s) failed to compile:\n" \
             "#{ext_errs.first(10).join("\n")}"
      end

      # ── 10. Generate miniinit_ruby.c with extension Init calls (Patch 3) ─
      miniinit_src = File.read(miniinit_path)

      ext_decls = ext_inits.map { |fn| "void #{fn}(void);" }.join("\n")
      ext_calls  = ext_inits.map { |fn| "    #{fn}();" }.join("\n")

      # Insert declarations just before the Init_ext function, then insert
      # calls inside Init_ext's body (before its closing brace).
      miniinit_ruby_src = miniinit_src
        .sub(
          /(?=\/\* miniruby does not support dynamic loading\. \*\/\nvoid\nInit_ext)/,
          "#{ext_decls}\n"
        )
        .sub(
          /(\/\* miniruby does not support dynamic loading\. \*\/\nvoid\nInit_ext\(void\)\n\{[^}]*)\}/m,
          "\\1#{ext_calls}\n}"
        )

      miniinit_ruby_path = File.join(build_dir, 'miniinit_ruby.c')
      File.write(miniinit_ruby_path, miniinit_ruby_src)

      miniinit_ruby_obj = File.join(build_dir, 'miniinit_ruby.o')
      r = occ_compile(miniinit_ruby_path, output: miniinit_ruby_obj,
                      flags: ext_base_flags + ['-DEXTSTATIC=1'])
      expect(r[:status]).to eq(0),
        "miniinit_ruby.c compile failed:\n#{r[:stderr].slice(0, 2000)}"

      # ── 11. Link full ruby binary ──────────────────────────────────────
      ruby_objs = obj_files.reject { |f| f.end_with?('miniinit.o') } +
                  [miniinit_ruby_obj] + ext_obj_files
      ruby_bin  = File.join(build_dir, 'ruby')

      link_flags = ['-lpthread', '-ldl', '-lm', '-liconv', '-lz',
                    '-framework', 'CoreFoundation']
      link_flags += ["-L#{libyaml_prefix}/lib", '-lyaml'] if libyaml_prefix
      link_flags += ['-lffi']                              if ffi_include
      link_flags += ["-L#{openssl_prefix}/lib", '-lssl', '-lcrypto'] if openssl_prefix

      _, ruby_link_err, ruby_link_st = Open3.capture3(
        'clang', *ruby_objs, '-o', ruby_bin, *link_flags
      )
      expect(ruby_link_st.exitstatus).to eq(0),
        "ruby link failed:\n#{ruby_link_err.slice(0, 5000)}"

      # ── 12. Full-ruby smoke tests ─────────────────────────────────────
      ruby_env = miniruby_env.merge('RUBYLIB' => nil)
      rb = ->(code, expected, label = nil) {
        label ||= code.length > 60 ? "#{code[0, 57]}..." : code
        out, err, st = Open3.capture3(ruby_env, ruby_bin, '-e', code)
        expect(st.exitstatus).to eq(0),
          "#{label}: non-zero exit\n#{err.slice(0, 2000)}"
        expect(out.strip).to eq(expected.strip), label
      }

      # Sanity: same basic arithmetic works
      rb.call 'puts 1 + 1',                   '2', 'ruby basic arithmetic'
      rb.call 'puts "hello from occ ruby"',   'hello from occ ruby', 'ruby puts'

      # StringIO
      rb.call 'require "stringio"; s = StringIO.new; s.puts "hi"; puts s.string.chomp',
              'hi', 'stringio'

      # Date
      rb.call 'require "date"; puts Date.new(2024, 3, 14).strftime("%Y-%m-%d")',
              '2024-03-14', 'date strftime'

      # Zlib roundtrip
      rb.call 'require "zlib"; d = Zlib::Deflate.deflate("hello world"); ' \
              'puts Zlib::Inflate.inflate(d)',
              'hello world', 'zlib roundtrip'

      # Digest
      rb.call 'require "digest"; puts Digest::MD5.hexdigest("hello")',
              '5d41402abc4b2a76b9719d911017c592', 'digest md5'
      rb.call 'require "digest"; puts Digest::SHA256.hexdigest("").length',
              '64', 'digest sha256 length'

      # JSON
      rb.call 'require "json"; h = JSON.parse(\'{"x":42}\'); puts h["x"]',
              '42', 'json parse'
      rb.call 'require "json"; puts JSON.generate({a: 1, b: [2, 3]})',
              '{"a":1,"b":[2,3]}', 'json generate'

      # StdLib (no external dep)
      rb.call 'require "strscan"; s = StringScanner.new("hello world"); ' \
              's.scan(/\w+/); puts s.pos',
              '5', 'strscan'
      rb.call 'require "pathname"; puts Pathname.new("/tmp/foo/bar").basename.to_s',
              'bar', 'pathname'

      if libyaml_prefix
        rb.call 'require "psych"; h = Psych.safe_load("a: 1\nb: 2"); puts h["b"]',
                '2', 'psych load'
        rb.call 'require "psych"; puts Psych.dump({"x" => 99}).include?("x:")',
                'true', 'psych dump'
      end

      if ffi_include
        rb.call 'require "fiddle"; puts Fiddle::SIZEOF_INT',
                '4', 'fiddle sizeof_int'
      end

    ensure
      puts "Build dir kept at: #{build_dir}"
    end
  end
end
