# frozen_string_literal: true

require 'open3'
require 'fileutils'

# Phase 11 Tier 4: CRuby 3.4 (miniruby)
#
# Compiles the CRuby interpreter using occ and verifies that the resulting
# miniruby binary can execute basic Ruby programs.
#
# Prerequisites (Phase 13 — GCC Extension Compatibility):
#   - Statement expressions ({ ... })
#   - __typeof__ with correct type reflection
#   - __builtin_offsetof computing correct offsets
#   - Alternate keyword spellings (__inline__, __volatile__, __asm__, etc.)
#   - __extension__ as a no-op keyword
#   - __builtin_clz / __builtin_ctz / __builtin_popcount
#   - Inline assembly (asm volatile("" ::: "memory"))
#
# Build strategy:
#   1. Clone ruby/ruby at a known tag
#   2. Run ./autogen.sh + ./configure using the system toolchain to generate
#      config.h, ruby/config.h, and other autoconf artefacts (occ is not used
#      for this step — configure requires a fully working C compiler)
#   3. Compile each miniruby source file to a .o with occ
#   4. Link all objects into miniruby using clang
#   5. Run smoke tests
#
# Run with:
#   THIRDPARTY=1 bundle exec rspec spec/phase11/ruby_spec.rb

RSpec.describe 'Phase 11: CRuby 3.4 miniruby (Tier 4)', :thirdparty do
  include ThirdpartyHelper

  RUBY_TAG    = 'v3_4_0'
  RUBY_REPO   = 'https://github.com/ruby/ruby.git'
  RUBY_CACHE  = File.join(ThirdpartyHelper::CACHE_DIR, 'ruby')

  # Files that form miniruby (the minimal interpreter without C extensions).
  # Generated by running `make minirubymain` and inspecting the link command.
  # Keep in sync with the Ruby version being tested.
  MINIRUBY_SOURCES = %w[
    main.c
    ruby.c
    array.c
    bignum.c
    class.c
    compar.c
    compile.c
    complex.c
    dir.c
    dln.c
    encoding.c
    enum.c
    enumerator.c
    error.c
    eval.c
    file.c
    gc.c
    hash.c
    io.c
    iseq.c
    load.c
    marshal.c
    math.c
    mjit.c
    node.c
    numeric.c
    object.c
    pack.c
    parse.c
    proc.c
    random.c
    range.c
    rational.c
    re.c
    regcomp.c
    regenc.c
    regerror.c
    regexec.c
    regparse.c
    regsyntax.c
    ruby_exts.c
    signal.c
    sprintf.c
    st.c
    strftime.c
    string.c
    struct.c
    symbol.c
    thread.c
    time.c
    transcode.c
    util.c
    variable.c
    version.c
    vm.c
    vm_backtrace.c
    vm_dump.c
    vm_exec.c
    vm_method.c
    vm_trace.c
  ].freeze

  def autotools_available?
    system('which autoconf > /dev/null 2>&1') &&
      system('which ./configure > /dev/null 2>&1 || true')
  end

  def run_configure(build_dir)
    # autogen.sh generates ./configure from configure.ac
    unless system('bash autogen.sh > /dev/null 2>&1', chdir: build_dir)
      skip 'ruby autogen.sh failed — autoconf may not be installed'
    end

    # Run configure with system clang to produce config.h and friends.
    # --disable-rubygems and --without-* keep the build minimal.
    configure_flags = %w[
      --disable-rubygems
      --disable-install-doc
      --without-gmp
      --with-static-linked-ext
    ]
    out, err, st = Open3.capture3(
      './configure', *configure_flags,
      chdir: build_dir
    )
    unless st.success?
      skip "ruby ./configure failed:\n#{err.slice(0, 500)}"
    end
  end

  it 'compiles miniruby and runs basic scripts', :slow do
    require_git!
    skip 'autoconf not available' unless system('which autoconf > /dev/null 2>&1')

    # ── 1. Clone source ────────────────────────────────────────────────────
    src_dir = git_clone(RUBY_REPO, RUBY_TAG, 'ruby')

    Dir.mktmpdir('occ_ruby_') do |build_dir|
      # Copy source into build dir so configure can write files there
      FileUtils.cp_r(Dir["#{src_dir}/*"], build_dir)
      FileUtils.cp_r(Dir["#{src_dir}/.[^.]*"].select { |f| File.file?(f) }, build_dir)

      # ── 2. Run ./configure with system toolchain ───────────────────────
      run_configure(build_dir)

      # ── 3. Generate parser (parse.c) via make if needed ───────────────
      # Ruby's parse.c is generated from parse.y; run it with system tools
      system('make parse.c BASERUBY=ruby 2>/dev/null', chdir: build_dir)

      # Collect include paths that configure produces
      include_flags = [
        "-I#{build_dir}",
        "-I#{build_dir}/include",
        "-I#{build_dir}/.ext/include/arm64-darwin",
        "-I#{build_dir}/.ext/include/universal-darwin",
      ].select { |f| Dir.exist?(f.sub('-I', '')) }
      include_flags += ['-I', ThirdpartyHelper::SDK_INCLUDE] if ThirdpartyHelper::SDK_INCLUDE

      # ── 4. Compile each miniruby source file with occ ──────────────────
      obj_files = []
      compile_errors = []

      MINIRUBY_SOURCES.each do |src_name|
        src_path = File.join(build_dir, src_name)
        next unless File.exist?(src_path)

        obj_path = File.join(build_dir, src_name.sub('.c', '.o'))
        result = occ_compile(
          src_path,
          output: obj_path,
          flags: include_flags + ['-c', '-DRUBY_EXPORT', '-DMINIRUBY']
        )

        if result[:status] == 0
          obj_files << obj_path
        else
          compile_errors << "#{src_name}: #{result[:stderr].lines.first&.strip}"
        end
      end

      # Report compile errors but don't fail immediately — show progress
      if compile_errors.any?
        fail "#{compile_errors.length} file(s) failed to compile:\n" \
             "#{compile_errors.first(10).join("\n")}"
      end

      expect(obj_files).not_to be_empty, 'no object files were produced'

      # ── 5. Link miniruby with clang ────────────────────────────────────
      miniruby_bin = File.join(build_dir, 'miniruby')
      _, link_err, link_st = Open3.capture3(
        'clang', *obj_files, '-o', miniruby_bin,
        '-lpthread', '-ldl', '-lm', '-liconv',
        '-framework', 'CoreFoundation'
      )
      expect(link_st.exitstatus).to eq(0),
        "link failed:\n#{link_err.slice(0, 500)}"

      # ── 6. Smoke tests ────────────────────────────────────────────────
      out, _, st = Open3.capture3(miniruby_bin, '-e', 'puts 1 + 1')
      expect(st.exitstatus).to eq(0), 'miniruby exited non-zero on puts 1+1'
      expect(out.strip).to eq('2'), "expected '2', got '#{out.strip}'"

      out2, _, st = Open3.capture3(miniruby_bin, '-e', 'puts "hello from occ"')
      expect(out2.strip).to eq('hello from occ')

      out3, _, _st = Open3.capture3(miniruby_bin, '-e', 'puts [1,2,3].map{|x| x*x}.inspect')
      expect(out3.strip).to eq('[1, 4, 9]')
    end
  end
end
